base:
  project: Super_Resolution

data_path:
  train: data\train\HR
  test_HR: data\validation\HR
  test_LR: data\validation\LR

data_load:
  batch_size: 2
  buffer_size: 800
  HR_img_width: 384
  HR_img_height: 384
  LR_img_width: 96
  LR_img_height: 96

model:
  model_name: SRGAN
  num_res_blocks: 16
  num_filters: 64
  kernel_size: 3
  num_channels: 3
  upsampling_factor: 2
  strides: 1
  padding: same
  saved_path: saved_models

training:
  epochs: 100

test:
  num_samples: 10

loss:
  lambda: 0.001

reports:
  params: report\params.json
  logs: report\logs.json

generated_image_output_path: Results